version: '3.9'
services:
  db:  
    image: postgres:15-alpine
    restart: always
    ports:
      - 54320:5432

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db/db-production:/var/lib/postgresql/data

  db-test:  
    image: postgres:15-alpine
    restart: always
    ports:
      - 54321:5432

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db-test
    volumes:
      - ./db/db-test:/var/lib/postgresql/data
