version: '3.9'
services:
  db:  
    container_name: db
    image: postgres:15-alpine
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db/db-production:/var/lib/postgresql/data
    

  db-test:  
    container_name: db-test
    image: postgres:15-alpine
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db-test
    volumes:
      - ./db/db-test:/var/lib/postgresql/data
    

 
  rest_api:
    container_name: rest_api
    build: 
      context: ./REST_API
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./REST_API:/REST_API
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    command: "flask run --host=0.0.0.0"
    depends_on:
      - db
    
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - rest_api
    